apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gulbarga-university-pvc
  namespace: gulbarga-university-production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: gulbarga-university-sc