apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managex-university-pvc
  namespace: dev-managex-university
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: dev-university-sc