apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managex-university-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: stage-university-sc