apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managex-university-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: prod-university-sc