apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managex-university-pvc
  namespace: managex-university-production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managex-university-production