# Kustomization configuration for development environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-managex-university
namePrefix: managex-
labels:
  - pairs:
      environment: development
    includeSelectors: false
    includeTemplates: true
resources:
  - ../../base

# Patches for different Kubernetes resources
patches:
  # Patch for CronJob configuration
  - target:
      kind: CronJob
      name: university-cronjob
    patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: university-cronjob
        labels:
          app: university-cronjob
      spec:
        jobTemplate:
          spec:
            template:
              metadata:
                labels:
                  app: university-cronjob
              spec:
                containers:
                  - name: university-cronjob
                    image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_university:ef5720c314dc9318eddc68d93c2b2cbe655f8ac5-Dev-main-1008-pushed-by-surya1005

  # Patch for Deployment configuration
  - target:
      kind: Deployment
      name: university
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: university
        labels:
          app: managex-university
      spec:
        template:
          metadata:
            labels:
              app: managex-university
            annotations:
              kubernetes.io/change-cause: Update to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_university:ef5720c314dc9318eddc68d93c2b2cbe655f8ac5-Dev-main-1008-pushed-by-surya1005 
          spec:
            containers:
              - name: managex-university
                image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/managex_university:ef5720c314dc9318eddc68d93c2b2cbe655f8ac5-Dev-main-1008-pushed-by-surya1005
                resources:
                  requests:
                    cpu: 300m
                    memory: 512Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi

  # Patch for Ingress configuration
  - target:
      kind: Ingress
      name: university-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: university-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/f04628d3-ad1e-4def-93a2-ad0016b15acb
          alb.ingress.kubernetes.io/cors-allow-origin: >-
            https://greatifydev.university,https://www.greatifydev.university,https://*.greatifydev.university
      spec:
        rules:
          - http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: managex-university-service
                      port:
                        number: 80
        tls:
          - hosts:
              - greatifydev.university
            secretName: tls-secret

  # Patch for ConfigMap configuration
  - target:
      kind: ConfigMap
      name: university-server-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: university-server-config
      data:
        default: |
          # Map for real scheme from CloudFront
          map $http_x_forwarded_proto $real_scheme {
            default $http_x_forwarded_proto;
            ''      $scheme;
          }


          # HTTP server block - CloudFront will handle HTTPS termination
          server {
            listen 80;
            listen [::]:80;
            server_name greatifydev.university www.greatifydev.university *.greatifydev.university;

            # Set the real IP from CloudFront and ALB
            real_ip_header X-Forwarded-For;
            set_real_ip_from 0.0.0.0/0; 
            real_ip_recursive on;

            # Specify the root directory for your application
            root /var/www/html/public;
            
            # CORS (Cross-Origin Resource Sharing) headers for API access
            set $cors_origin '';
            if ($http_origin ~* ^https?://(localhost:[0-9]+|([a-z0-9-]+\.)?greatifydev\.university(:[0-9]+)?)$) {
                set $cors_origin $http_origin;
            }
            add_header 'Access-Control-Allow-Origin' $cors_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
            add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Vary' 'Origin' always;
            
            # Security headers
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;

            # Specify index files
            index index.php index.html index.htm;

            # Set character encoding
            charset utf-8;

            # Set maximum client body size
            client_max_body_size 1024M;

            # Main location block for handling requests
            location / {
                try_files $uri $uri/ /index.php?$query_string;
            }


            # Handle favicon and robots.txt requests separately
            location = /favicon.ico {
                access_log off;
                log_not_found off;
            }
            
            location = /robots.txt {
                access_log off;
                log_not_found off;
            }


            # Error page handling for 404 errors
            error_page 404 /index.php;


            # Error page handling for 502, 503, and 504 errors
            error_page 502 503 504 /error.html;


            # PHP handling configuration
            location ~ \.php$ {
                include snippets/fastcgi-php.conf;  # Default PHP handling snippet

                # Pass PHP requests to the PHP-FPM socket
                fastcgi_pass unix:/run/php/php8.3-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }


            # Restrict access to hidden files
            location ~ /\.(?!well-known).* {
                deny all;
            }


            # Enhance security with rate limiting (Uncomment to enable)
            # limit_req zone=mylimit burst=10 nodelay;
            
            # Enable gzip compression (Uncomment to enable)
            gzip on;
            gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
          }
          
  # Patch for SecretProviderClass configuration
  - target:
      kind: SecretProviderClass
      name: university-secrets
    patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: university-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:Managex-University-Dev-7x2By5
              objectAlias: ".env"
              objectType: "secretsmanager"